server:
  port: 8111

spring:  application:    name: ApiGateway
      cloud:    gateway:      routes:      - id: hello
        uri: http://localhost:9095/
        predicates:        - Path=/hello/**
        filters:
        - RewritePath=/service(?<segment>/?.*), $\{segment}
        
      - id: todo
        uri: http://localhost:8080/
        predicates:
        - Path=/todo/**
        filters:
        - RewritePath=/service(?<segment>/?.*), $\{segment}
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
